declare function _default(__exports: any): {
    newJSVal: (v: any) => number;
    getJSVal: (k: any) => any;
    freeJSVal: (k: any) => void;
    scheduleWork: () => any;
    ZC0ZCcassiezmclizm0zi1zi0zi0zminplacezmreactorZCJSFileSystemZC: ($1: any) => any;
    ZC1ZCcassiezmclizm0zi1zi0zi0zminplacezmreactorZCJSFileSystemZC: () => any;
    ZC2ZCcassiezmclizm0zi1zi0zi0zminplacezmreactorZCJSFileSystemZC: () => any;
    ZC3ZCcassiezmclizm0zi1zi0zi0zminplacezmreactorZCJSFileSystemZC: ($1: any, $2: any) => any;
    ZC4ZCcassiezmclizm0zi1zi0zi0zminplacezmreactorZCJSFileSystemZC: ($1: any) => any;
    ZC5ZCcassiezmclizm0zi1zi0zi0zminplacezmreactorZCJSFileSystemZC: ($1: any, $2: any) => any;
    ZC6ZCcassiezmclizm0zi1zi0zi0zminplacezmreactorZCJSFileSystemZC: ($1: any) => any;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => any;
    ZC19ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any) => any;
    ZC20ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any) => void;
    ZC21ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: ($1: any, $2: any) => void;
    ZC22ZCghczminternalZCGHCziInternalziWasmziPrimziExportsZC: () => Promise<any>;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => string;
    ZC1ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any, $2: any) => string;
    ZC2ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any, $2: any, $3: any) => number;
    ZC3ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => any;
    ZC4ZCghczminternalZCGHCziInternalziWasmziPrimziTypesZC: ($1: any) => void;
    ZC18ZCghczminternalZCGHCziInternalziWasmziPrimziImportsZC: ($1: any, $2: any) => any;
    ZC0ZCghczminternalZCGHCziInternalziWasmziPrimziConcziInternalZC: ($1: any) => Promise<any>;
};
export default _default;
